FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /bidding-engine ./cmd/bidding

FROM alpine:3.21
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /bidding-engine .
COPY config*.yaml ./
EXPOSE 5160
CMD ["./bidding-engine"]
